Rewrote to be able to stop proxy by cluster name

diff --git a/stop-proxy b/stop-proxy
--- a/stop-proxy
+++ b/stop-proxy
@@ -3,11 +3,40 @@
 # Stop proxy
 #
 
+source utils.sh
+source config/proxy.conf
+
 echo ""
-readonly PS_COUNT=$(netstat -antp 2> /dev/null | grep kubectl | grep 8001 | wc -l)
-if (( ${PS_COUNT} == 0 )); then echo "Proxy not started..."; echo ""; exit 0; fi 
-echo "Stopping proxy..."
-sudo pkill kubectl > /dev/null 2>&1
+while getopts "n:h" opt ${@}; do
+        case ${opt} in
+                n)
+                        clusterName=${OPTARG}
+                        ;;
+                h)
+                        echo "Usage: "
+                        echo "        stop-proxy [-n cluster-name]"
+                        echo ""
+                        echo "        The default cluster name is [kind]"
+                        echo ""
+                        exit 0
+                        ;;
+        esac
+done
+
+readonly CLUSTER_NAME=${clusterName:-kind}
+readonly CTX_NAME="kind-${clusterName:-kind}"
+readonly PROXY_DATA_FILE=${DATA_DIR}/${CTX_NAME}
+
+echo "Stopping proxy for [${CLUSTER_NAME}] cluster..."
+if [ ! -f ${PROXY_DATA_FILE} ]; then
+	abort "Unable to locate proxy data file [${PROXY_DATA_FILE}] for [${CLUSTER_NAME}] cluster"
+fi
+source ${PROXY_DATA_FILE} 
+readonly checkData=$(netstat -antp 2> /dev/null | grep kubectl | grep ${PROXY_PORT})
+readonly processCount=$([ -z ${checkData}] && echo 0 || echo ${checkData} | wc -l) 
+if (( ${processCount} == 0 )); then echo "Proxy not running..."; echo ""; exit 0; fi 
+readonly processId=$(echo $checkData | awk '{print $7}' | awk 'BEGIN { FS = "/" } ; {print $1}')
+kill -9 ${processId} > /dev/null 2>&1
 if (( $? )); then echo "Failed to stop proxy"; echo ""; exit 1; fi 
 echo "Successfully stopped proxy"
 echo ""
